"""bikes and batteries

Revision ID: 311eee11fda7
Revises: 2316c10cffb3
Create Date: 2025-11-06 20:35:16.535092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '311eee11fda7'
down_revision: Union[str, Sequence[str], None] = '2316c10cffb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bikes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('available', 'assigned', 'maintenance', 'retired', name='bike_status'), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('last_service_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_profile_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_profile_id'], ['user_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_bikes_assigned_profile_id'), 'bikes', ['assigned_profile_id'], unique=False)
    op.create_index(op.f('ix_bikes_id'), 'bikes', ['id'], unique=False)
    op.create_table('batteries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('capacity_wh', sa.Integer(), nullable=True),
    sa.Column('charge_level', sa.Integer(), nullable=False),
    sa.Column('cycle_count', sa.Integer(), nullable=False),
    sa.Column('health_status', sa.Enum('good', 'degraded', 'poor', name='battery_health'), nullable=False),
    sa.Column('status', sa.Enum('available', 'assigned', 'charging', 'maintenance', 'retired', name='battery_status'), nullable=False),
    sa.Column('last_service_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_bike_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_bike_id'], ['bikes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_batteries_assigned_bike_id'), 'batteries', ['assigned_bike_id'], unique=False)
    op.create_index(op.f('ix_batteries_id'), 'batteries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batteries_id'), table_name='batteries')
    op.drop_index(op.f('ix_batteries_assigned_bike_id'), table_name='batteries')
    op.drop_table('batteries')
    op.drop_index(op.f('ix_bikes_id'), table_name='bikes')
    op.drop_index(op.f('ix_bikes_assigned_profile_id'), table_name='bikes')
    op.drop_table('bikes')
    # ### end Alembic commands ###
