"""user role

Revision ID: 58ea8688723b
Revises: 311eee11fda7
Create Date: 2025-11-11 18:10:22.850634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ea8688723b'
down_revision: Union[str, Sequence[str], None] = '311eee11fda7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Explicitly create the PostgreSQL enum type before adding the column (idempotent)
    role_enum = sa.Enum('admin', 'driver', name='role_enum')
    role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', role_enum, server_default='driver', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # Drop the enum type if no longer used
    role_enum = sa.Enum('admin', 'driver', name='role_enum')
    role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
