"""bike serial lowercase

Revision ID: 6e532896a9b2
Revises: 58ea8688723b
Create Date: 2025-11-12 14:01:45.292435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e532896a9b2'
down_revision: Union[str, Sequence[str], None] = '58ea8688723b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bikes', sa.Column('serial_number_ci', sa.String(), nullable=False))
    op.create_index(op.f('ix_bikes_serial_number_ci'), 'bikes', ['serial_number_ci'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bikes_serial_number_ci'), table_name='bikes')
    op.drop_column('bikes', 'serial_number_ci')
    # ### end Alembic commands ###
