"""financial transactions and maintenance

Revision ID: 751e1c522b4a
Revises: 8a92490a8f3a
Create Date: 2025-11-20 22:45:48.682758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '751e1c522b4a'
down_revision: Union[str, Sequence[str], None] = '8a92490a8f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bike_id', sa.UUID(), nullable=True),
    sa.Column('battery_id', sa.UUID(), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False, comment='What maintenance was performed'),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False, comment='Cost of the maintenance'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['battery_id'], ['batteries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bike_id'], ['bikes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_battery_id'), 'maintenance_records', ['battery_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_bike_id'), 'maintenance_records', ['bike_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_id'), 'maintenance_records', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_service_date'), 'maintenance_records', ['service_date'], unique=False)
    op.create_table('financial_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.Enum('income', 'expense', name='transaction_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rental_id', sa.UUID(), nullable=True),
    sa.Column('maintenance_record_id', sa.UUID(), nullable=True),
    sa.Column('transaction_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_record_id'], ['maintenance_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_transactions_id'), 'financial_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_maintenance_record_id'), 'financial_transactions', ['maintenance_record_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_rental_id'), 'financial_transactions', ['rental_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_transaction_date'), 'financial_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_financial_transactions_transaction_type'), 'financial_transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_transactions_transaction_type'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_transaction_date'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_rental_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_maintenance_record_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_id'), table_name='financial_transactions')
    op.drop_table('financial_transactions')
    op.drop_index(op.f('ix_maintenance_records_service_date'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_bike_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_battery_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    # ### end Alembic commands ###
