"""bike rentals

Revision ID: 8a92490a8f3a
Revises: 6e532896a9b2
Create Date: 2025-11-20 22:07:27.496099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a92490a8f3a'
down_revision: Union[str, Sequence[str], None] = '6e532896a9b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rentals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bike_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bike_id'], ['bikes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rentals_bike_id'), 'rentals', ['bike_id'], unique=False)
    op.create_index(op.f('ix_rentals_end_date'), 'rentals', ['end_date'], unique=False)
    op.create_index(op.f('ix_rentals_id'), 'rentals', ['id'], unique=False)
    op.create_index(op.f('ix_rentals_profile_id'), 'rentals', ['profile_id'], unique=False)
    op.create_index(op.f('ix_rentals_start_date'), 'rentals', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rentals_start_date'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_profile_id'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_id'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_end_date'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_bike_id'), table_name='rentals')
    op.drop_table('rentals')
    # ### end Alembic commands ###
